### ISSUE TITLE
Failed to compile

### ISSUE THREAD

**Issue by david-kohen** [chandrawi/U8x_Laser_Distance#1]
Hi - I tried building your code and it fails on 

/tmp/.arduinoIDE-unsaved2023418-32322-j1tvu0.dfinl/U8x_command/U8x_command.ino:4:34: error: no matching function for call to 'HardwareSerial::HardwareSerial(int, int)'
 HardwareSerial SerialU8x(PB7, PB6);
                                  ^
In file included from /home/dkohen/.arduino15/packages/arduino/hardware/avr/1.8.6/cores/arduino/Arduino.h:233:0,
                 from /tmp/arduino/sketches/506A0B1F7421F323E204B9927DA3416E/sketch/U8x_command.ino.cpp:1:
/home/dkohen/.arduino15/packages/arduino/hardware/avr/1.8.6/cores/arduino/HardwareSerial.h:117:12: note: candidate: HardwareSerial::HardwareSerial(volatile uint8_t*, volatile uint8_t*, volatile uint8_t*, volatile uint8_t*, volatile uint8_t*, volatile uint8_t*)
     inline HardwareSerial(
            ^~~~~~~~~~~~~~
.
.
.
.

exit status 1

Compilation error: no matching function for call to 'HardwareSerial::HardwareSerial(int, int)'

Could it be that you had a serial port definition that isn't included in the git files?

Regards

David

**Comment by chandrawi** [comment]
What kind of Arduino you used?

I was developing U8X library using blue pill and STM32Duino Arduino core.

The error happen because the Arduino sketch called constructor without supplying a `HardwareSerial` or `SoftwareSerial` object. In this case the default `Serial` object used.

There is no problem when I used STM32F1. But when I tried to compile using Arduino Pro mini I got similar error. So, I change the `#if` preprocessor for the constructor so the skecth can compile for both AVR and STM32 processor.

```cpp
#if defined(HAVE_HWSERIAL0) || (defined(Serial) && !defined(ENABLE_SERIALUSB))
        U8xLaser(int8_t pwrEn=-1, int8_t reset=-1);
#endif
```
I have updated the library. You can try to upload to your board using the latest commit on main branch.

**Comment by david-kohen** [comment]
Great - thank you so much for the quick response. That fixes the compile problem for the Mega and Uno.
